import { httpsCallable } from 'firebase/functions'
import { addDoc, collection } from 'firebase/firestore'
import { db, functions } from '../firebase'
import type { Invoice, InvoiceLine, Estimate, ChangeOrder } from '../data/types'
import type { BusinessProfile } from '../Settings'

const generateInvoiceCopyCallable = httpsCallable<
  {
    clerkToken: string
    input: {
      customerName: string
      jobTypeName: string
      businessName?: string
      contractorName?: string
      total: number
      amountPaid?: number
      dueInDays?: number
      paymentMethods?: string
    }
  },
  { intro_note: string; payment_terms: string }
>(functions, 'generateInvoiceCopy')

interface BuildInvoiceArgs {
  clerkToken: string
  userId: string
  project: {
    id: string
    customerName: string
    customerId?: string
    jobTypeName: string
    jobLocationZip?: string
  }
  customerEmail?: string
  customerPhone?: string
  customerAddress?: string
  estimates: Estimate[]              // estimates linked to this project
  changeOrders: ChangeOrder[]        // change orders linked to this project (approved/pending — caller filters)
  profile: BusinessProfile
  contractorName?: string
  amountPaid?: number                // deposits already received, optional
  dueInDays?: number                 // default 14
  invoiceNumber: string              // generated by caller (e.g. INV-2026-0001)
}

// Builds an Invoice doc by:
//   1) Rolling up line items from estimate(s) + approved change orders
//   2) Calling the Cloud Function to get AI-written intro + payment terms
//   3) Persisting the result to invoices/{id}
//
// Returns the saved Invoice (with id).
export async function createInvoice(args: BuildInvoiceArgs): Promise<Invoice> {
  const { clerkToken, userId, project, estimates, changeOrders, profile } = args
  if (!clerkToken) throw new Error('Not signed in')

  // ── 1. Line items
  // Prefer the first estimate's AI quote (richest data). Fall back to a single
  // line representing the estimate total if no AI quote exists.
  const lineItems: InvoiceLine[] = []
  const primaryEstimate = estimates[0]

  if (primaryEstimate?.aiQuote && primaryEstimate.aiQuote.material_list.length > 0) {
    // Materials line items
    for (const m of primaryEstimate.aiQuote.material_list) {
      lineItems.push({
        name: m.name,
        quantity: m.quantity_with_waste,
        unitPrice: m.unit_price,
        lineTotal: m.line_total,
      })
    }
    // Labor as a single line
    const labor = primaryEstimate.aiQuote.labor
    if (labor && labor.labor_total > 0) {
      lineItems.push({
        name: `Labor — ${labor.estimated_hours} hours @ $${labor.hourly_rate}/hr`,
        quantity: 1,
        unitPrice: labor.labor_total,
        lineTotal: labor.labor_total,
      })
    }
    // Rentals as a single line if any
    const rentals = primaryEstimate.aiQuote.price_breakdown.rentals_subtotal
    if (rentals && rentals > 0) {
      lineItems.push({
        name: 'Rental equipment',
        quantity: 1,
        unitPrice: rentals,
        lineTotal: rentals,
      })
    }
  } else if (primaryEstimate) {
    // No structured AI quote — single roll-up line.
    lineItems.push({
      name: `${project.jobTypeName} (per estimate)`,
      quantity: 1,
      unitPrice: primaryEstimate.total || 0,
      lineTotal: primaryEstimate.total || 0,
    })
  }

  // Change orders — only include approved ones (declined/pending should NOT
  // appear on the final invoice).
  for (const co of changeOrders.filter(c => c.status === 'approved')) {
    lineItems.push({
      name: `Change Order: ${co.description}`,
      quantity: 1,
      unitPrice: co.delta,
      lineTotal: co.delta,
    })
  }

  const subtotal = +lineItems.reduce((s, l) => s + l.lineTotal, 0).toFixed(2)
  const amountPaid = +(args.amountPaid || 0).toFixed(2)
  const amountDue = +(subtotal - amountPaid).toFixed(2)
  const dueInDays = args.dueInDays ?? 14
  const dueDate = new Date(Date.now() + dueInDays * 24 * 60 * 60 * 1000).toISOString()

  // ── 2. Cover copy (intro + payment terms). Try the generator, but if it's
  // unavailable (e.g. the free tier is used up), fall back to clean default
  // wording so the invoice still gets created. The contractor can edit it.
  let intro_note: string
  let payment_terms: string
  try {
    const copyRes = await generateInvoiceCopyCallable({
      clerkToken,
      input: {
        customerName: project.customerName,
        jobTypeName: project.jobTypeName,
        businessName: profile.businessName || undefined,
        contractorName: args.contractorName,
        total: subtotal,
        amountPaid: amountPaid > 0 ? amountPaid : undefined,
        dueInDays,
      },
    })
    intro_note = copyRes.data.intro_note
    payment_terms = copyRes.data.payment_terms
  } catch (err) {
    console.warn('Invoice copy generator unavailable — using default wording.', err)
    const biz = profile.businessName || args.contractorName || 'us'
    intro_note = `Thank you for choosing ${biz} for your ${project.jobTypeName.toLowerCase()}. Please find your invoice details below.`
    payment_terms = `Payment is due within ${dueInDays} days. Please reach out with any questions about this invoice.`
  }

  // ── 3. Persist
  const payload: Record<string, unknown> = {
    projectId: project.id,
    customerName: project.customerName,
    jobTypeName: project.jobTypeName,
    invoiceNumber: args.invoiceNumber,
    introNote: intro_note,
    paymentTerms: payment_terms,
    lineItems,
    subtotal,
    amountPaid,
    amountDue,
    status: 'sent',
    dueDate,
    createdAt: new Date().toISOString(),
    createdBy: userId,
  }
  if (project.jobLocationZip) payload.jobLocationZip = project.jobLocationZip
  if (args.customerEmail) payload.customerEmail = args.customerEmail
  if (args.customerPhone) payload.customerPhone = args.customerPhone
  if (args.customerAddress) payload.customerAddress = args.customerAddress
  if (profile.businessName) payload.businessName = profile.businessName
  if (profile.businessPhone) payload.businessPhone = profile.businessPhone
  if (profile.businessEmail) payload.businessEmail = profile.businessEmail
  if (profile.licenseNumber) payload.licenseNumber = profile.licenseNumber
  if (profile.logoUrl) payload.logoUrl = profile.logoUrl
  if (args.contractorName) payload.contractorName = args.contractorName

  const ref = await addDoc(collection(db, 'invoices'), payload)
  return { id: ref.id, ...payload } as Invoice
}

// Creates a DEPOSIT invoice the moment a customer approves an estimate that
// requested an upfront deposit. It states the work order (from the estimate
// scope), the deposit due now, and the balance due at completion. No AI call —
// the wording is deterministic so it's instant and reliable.
export async function createDepositInvoice(args: {
  userId: string
  estimate: Estimate
  project: { id: string }
  profile: BusinessProfile
  contractorName?: string
  customerEmail?: string
  customerPhone?: string
  customerAddress?: string
  invoiceNumber: string
}): Promise<Invoice> {
  const { userId, estimate, project, profile } = args
  const deposit = +(estimate.depositAmount || 0).toFixed(2)
  const jobTotal = +(estimate.total || 0).toFixed(2)
  const balance = +Math.max(0, jobTotal - deposit).toFixed(2)

  const lineItems: InvoiceLine[] = [{
    name: `Deposit to begin work — ${estimate.jobTypeName}`,
    quantity: 1,
    unitPrice: deposit,
    lineTotal: deposit,
  }]

  // Work order / steps pulled from the estimate's scope, plus clear deposit terms.
  const introNote = `Thank you for approving your ${estimate.jobTypeName.toLowerCase()}. This invoice is for the deposit to schedule and begin the work. Once it's paid, we'll lock in your start date.`
  const paymentTerms =
    `WORK ORDER\n${(estimate.scopeOfWork || estimate.description || estimate.jobTypeName).trim()}\n\n` +
    `PAYMENT TERMS\n` +
    `• Total job: $${jobTotal.toFixed(2)}\n` +
    `• Deposit due now (this invoice): $${deposit.toFixed(2)}\n` +
    `• Balance due at completion: $${balance.toFixed(2)}\n\n` +
    `Work begins once the deposit is received. The remaining balance is invoiced when the job is finished and you've had a chance to look it over.`

  const payload: Record<string, unknown> = {
    projectId: project.id,
    customerName: estimate.customerName,
    jobTypeName: `${estimate.jobTypeName} — Deposit`,
    invoiceNumber: args.invoiceNumber,
    introNote,
    paymentTerms,
    lineItems,
    subtotal: deposit,
    amountPaid: 0,
    amountDue: deposit,
    status: 'sent',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    isDeposit: true,
    createdAt: new Date().toISOString(),
    createdBy: userId,
  }
  if (estimate.jobLocationZip) payload.jobLocationZip = estimate.jobLocationZip
  if (args.customerEmail) payload.customerEmail = args.customerEmail
  if (args.customerPhone) payload.customerPhone = args.customerPhone
  if (args.customerAddress) payload.customerAddress = args.customerAddress
  if (profile.businessName) payload.businessName = profile.businessName
  if (profile.businessPhone) payload.businessPhone = profile.businessPhone
  if (profile.businessEmail) payload.businessEmail = profile.businessEmail
  if (profile.licenseNumber) payload.licenseNumber = profile.licenseNumber
  if (profile.logoUrl) payload.logoUrl = profile.logoUrl
  if (args.contractorName) payload.contractorName = args.contractorName

  const ref = await addDoc(collection(db, 'invoices'), payload)
  return { id: ref.id, ...payload } as Invoice
}

// Re-runs ONLY the cover copy (intro note + payment terms) for an existing
// invoice — used by the "Regenerate wording" button in the invoice editor.
export async function regenerateInvoiceCopy(args: {
  clerkToken: string
  customerName: string
  jobTypeName: string
  businessName?: string
  contractorName?: string
  subtotal: number
  amountPaid?: number
  dueInDays?: number
  paymentMethods?: string
}): Promise<{ introNote: string; paymentTerms: string }> {
  const res = await generateInvoiceCopyCallable({
    clerkToken: args.clerkToken,
    input: {
      customerName: args.customerName,
      jobTypeName: args.jobTypeName,
      businessName: args.businessName,
      contractorName: args.contractorName,
      total: args.subtotal,
      amountPaid: args.amountPaid && args.amountPaid > 0 ? args.amountPaid : undefined,
      dueInDays: args.dueInDays,
      paymentMethods: args.paymentMethods,
    },
  })
  return { introNote: res.data.intro_note, paymentTerms: res.data.payment_terms }
}

// Generates the next invoice number for a user. Simple format: INV-YYYY-NNNN
// where NNNN increments per user per year. Falls back to timestamp-based if
// the count lookup fails.
export function nextInvoiceNumber(existingCount: number): string {
  const year = new Date().getFullYear()
  const n = String(existingCount + 1).padStart(4, '0')
  return `INV-${year}-${n}`
}
